/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cloud_logic_custom": [
        {
            "name": "helloWorldAPI",
            "endpoint": "https://wfyamhb23c.execute-api.us-west-1.amazonaws.com/dev",
            "region": "us-west-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://tqzpwvr2tzahnlkl3jwqtxjfiq.appsync-api.us-west-1.amazonaws.com/graphql",
};


export default awsmobile;
